AWSTemplateFormatVersion: '2010-09-09'
# Output resource

Resources:
  MyTestVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true

