AWSTemplateFormatVersion: 2010-09-09
Description: Template for nextgen network infrastructure
Resources: 
  NextGenProdVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Env
        Value: production
      - Key: Name
        Value: NextGenProdVPC
        
# NextGen Webserver subnet
  NextGenProdVPCWebserverSN:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: NextGenProdVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: NextGenProdVPCWebserverSN
