AWSTemplateFormatVersion: 2010-09-09
Description: This template provisions Next Gen Prod Webserver
Metadata: {}

Parameters: 
  # Instance type for Webservers
  NextGenProdWebserverInstanceType:
    Description: Please select an instance type for your prod webserver
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.medium
    ConstraintDescription: Selected value not supported

  NextGenProdWebserverKeyName:
    Description: Please select a key pair
    Type: AWS::EC2::KeyPair::KeyName

  # Instance type for Appservers
  NextGenProdappserverInstanceType:
    Description: Please select an instance type for your prod appserver
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.large
      - t2.xlarge
    ConstraintDescription: Selected value not supported

  NextGenProdappserverKeyName:
    Description: Please select a key pair
    Type: AWS::EC2::KeyPair::KeyName


Mappings: 
  NextGenserverGoldenAMIMap: 
    us-east-1:
      GoldenAMI: ami-09538990a0c4fe9be
    us-east-2:
      GoldenAMI: ami-098dd3a86ea110896
    us-west-1:
      GoldenAMI: ami-09c72d5a7ce529ad5
    us-west-2:
      GoldenAMI: ami-089ffe32605122764

Conditions: {}


Resources: 
# Webserver 1
  NextGenProdWebserver1:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue NextGenProdVPCWebserverSubnet1ID
      KeyName: !Ref NextGenProdWebserverKeyName
      ImageId: !FindInMap [ NextGenserverGoldenAMIMap, !Ref "AWS::Region", GoldenAMI ]
      InstanceType: !Ref NextGenProdWebserverInstanceType
      SecurityGroupIds: 
        - !ImportValue NextGenProdWebserverSGID
      Tags:
        - Key: Name
          Value: NextGenProdWebserver1

# Webserver 2
  NextGenProdWebserver2:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue NextGenProdVPCWebserverSubnet2ID 
      KeyName: !Ref NextGenProdWebserverKeyName
      ImageId: !FindInMap [ NextGenserverGoldenAMIMap, !Ref "AWS::Region", GoldenAMI ]
      InstanceType: !Ref NextGenProdWebserverInstanceType
      SecurityGroupIds: 
        - !ImportValue NextGenProdWebserverSGID
      Tags:
          - Key: Name
            Value: NextGenProdWebserver2

# Appserver 1
  NextGenProdappserver1:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue NextGenProdVPCAppserverSubnet1ID
      KeyName: !Ref NextGenProdapperverKeyName
      ImageId: !FindInMap [ NextGenserverGoldenAMIMap, !Ref "AWS::Region", GoldenAMI ]
      InstanceType: !Ref NextGenProdappserverInstanceType
      SecurityGroupIds: 
        - !ImportValue NextGenProdAppserverSGID
      Tags:
        - Key: Name
          Value: NextGenProdappserver1

# Appserver 2
  NextGenProdappserver2:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue NextGenProdVPCAppserverSubnet2ID
      KeyName: !Ref NextGenProdappserverKeyName
      ImageId: !FindInMap [ NextGenserverGoldenAMIMap, !Ref "AWS::Region", GoldenAMI ]
      InstanceType: !Ref NextGenProdappserverInstanceType
      SecurityGroupIds: 
        - !ImportValue NextGenProdAppserverSGID
      Tags:
          - Key: Name
            Value: NextGenProdappserver2

