---
AWSTemplateFormatVersion: "2010-09-09"
Description: This is the first cloudformation template to create S3 bucket and EC2 instance along with parameters section

Parameters:
# EC2 parameter
  EC2AMIID:
    Type: String
    Default: ami-026b57f3c383c2eec
    AllowedValues:
      - ami-026b57f3c383c2eec
      - ami-07a53499a088e4a8c
    Description: Enter ami id
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.

  S3BucketnameP:
   Type: String

Resources:
  MyDemoS3bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref S3BucketnameP
  MyDemoEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref EC2AMIID
      InstanceType: !Ref InstanceTypeParameter


 


  



